// AUTO-GENERATED by scripts/figma-process-section.mjs — DO NOT EDIT MANUALLY.
// Source: web-output/stape-v2/sections/metrics-band/source.raw.jsx
// Figma node: 310:841 (file DycBk4R0tH1h3XH1F2xifX)
// Regenerate: node scripts/figma-process-section.mjs metrics-band

import React from 'react';

const imgImage6 = "/stape-website/v2-assets/metrics-band/d10c1ea8971f8551c7963462300791555b0fff7e.png";

export default function SectionMetricsBand() {
  return (
    <div className="contents relative size-full" data-name="section/metrics-band" data-node-id="310:841">
      <div className="absolute gap-x-[10px] grid grid-cols-[repeat(5,minmax(0,1fr))] grid-rows-[repeat(1,fit-content(100%))] left-[50px] top-[0px] w-[1340px]" data-node-id="310:842">
        <div className="bg-[#f5f5f5] col-[1/span_2] content-stretch flex flex-col items-start justify-between justify-self-stretch overflow-clip p-[20px] relative rounded-[20px] row-start-1 self-stretch shrink-0" data-node-id="310:843">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.36] not-italic relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:844" style={{ fontFeatureSettings: "'ss02'" }}>
            Fixed Per Payout
          </p>
          <div className="h-[80px] relative shrink-0 w-full" data-node-id="310:845">
            <p className="absolute bottom-[75px] font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] left-0 not-italic text-[#1b1b1b] text-[80px] tracking-[-1.6px] translate-y-full whitespace-nowrap" data-node-id="310:846">
              €50
            </p>
          </div>
        </div>
        <div className="bg-[#f5f5f5] col-start-4 content-stretch flex flex-col h-[260px] items-start justify-between justify-self-stretch not-italic overflow-clip p-[20px] relative rounded-[20px] row-start-1 shrink-0" data-node-id="310:847">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.4] relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:848" style={{ fontFeatureSettings: "'ss02'" }}>
            Contractor onboarding
          </p>
          <p className="font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] relative shrink-0 text-[#141414] text-[32px] tracking-[-0.64px] w-full" data-node-id="310:849">
            2 hours
          </p>
        </div>
        <div className="bg-[#f5f5f5] col-start-5 content-stretch flex flex-col h-[260px] items-start justify-between justify-self-stretch overflow-clip p-[20px] relative rounded-[20px] row-start-1 shrink-0" data-node-id="310:850">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.4] not-italic relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:851" style={{ fontFeatureSettings: "'ss02'" }}>{`SO/IEC 27001 & GDPR Compliant`}</p>
          <div className="content-stretch flex flex-col h-[32px] items-start justify-center relative shrink-0 w-full" data-node-id="310:852">
            <div className="h-[34px] opacity-92 relative shrink-0 w-[47px]" data-name="image 6" data-node-id="310:853">
              <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <img alt="" className="absolute h-full left-[-15.5%] max-w-none top-0 w-[116%]" src={imgImage6} />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-[#f5f5f5] col-start-3 content-stretch flex flex-col h-[260px] items-start justify-between justify-self-stretch not-italic overflow-clip p-[20px] relative rounded-[20px] row-start-1 shrink-0" data-node-id="310:854">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.4] relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:855" style={{ fontFeatureSettings: "'ss02'" }}>
            Teams where payroll just happens
          </p>
          <p className="font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] relative shrink-0 text-[#141414] text-[32px] tracking-[-0.64px] w-full" data-node-id="310:856">
            600+
          </p>
        </div>
      </div>
      <div className="absolute gap-x-[10px] grid grid-cols-[repeat(5,minmax(0,1fr))] grid-rows-[repeat(1,fit-content(100%))] left-[50px] top-[270px] w-[1340px]" data-node-id="310:857">
        <div className="bg-[#f5f5f5] col-start-3 content-stretch flex flex-col items-start justify-between justify-self-stretch not-italic overflow-clip p-[20px] relative rounded-[20px] row-start-1 self-stretch shrink-0" data-node-id="310:858">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.4] relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:859" style={{ fontFeatureSettings: "'ss02'" }}>
            From signup to first payment
          </p>
          <p className="font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] relative shrink-0 text-[#141414] text-[32px] tracking-[-0.64px] w-full" data-node-id="310:860">
            1 day
          </p>
        </div>
        <div className="bg-[#f5f5f5] col-[4/span_2] content-stretch flex flex-col h-[260px] items-start justify-between justify-self-stretch overflow-clip p-[20px] relative rounded-[20px] row-start-1 shrink-0" data-node-id="310:861">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.36] not-italic relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:862" style={{ fontFeatureSettings: "'ss02'" }}>
            Fixed Per Payout
          </p>
          <div className="h-[80px] relative shrink-0 w-full" data-node-id="310:863">
            <p className="absolute bottom-[75px] font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] left-0 not-italic text-[#1b1b1b] text-[80px] tracking-[-1.6px] translate-y-full whitespace-nowrap" data-node-id="310:864">
              $40M+
            </p>
          </div>
        </div>
        <div className="bg-[#f5f5f5] col-start-2 content-stretch flex flex-col items-start justify-between justify-self-stretch overflow-clip p-[20px] relative rounded-[20px] row-start-1 self-stretch shrink-0" data-node-id="310:865">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.36] not-italic relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:866" style={{ fontFeatureSettings: "'ss02'" }}>
            Contractor fee
          </p>
          <div className="h-[80px] relative shrink-0 w-full" data-node-id="310:867">
            <p className="absolute bottom-[75px] font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] left-0 not-italic text-[#1b1b1b] text-[80px] tracking-[-1.6px] translate-y-full whitespace-nowrap" data-node-id="310:868">
              Zero
            </p>
          </div>
        </div>
        <div className="bg-[#f5f5f5] col-start-1 content-stretch flex flex-col items-start justify-between justify-self-stretch not-italic overflow-clip p-[20px] relative rounded-[20px] row-start-1 self-stretch shrink-0" data-node-id="310:869">
          <p className="font-['ABC_Schengen_A_Cyrillic:Regular',sans-serif] leading-[1.4] relative shrink-0 text-[#727272] text-[16px] tracking-[0.16px] w-full" data-node-id="310:870" style={{ fontFeatureSettings: "'ss02'" }}>
            Locations Covered
          </p>
          <p className="font-['ABC_Schengen_A_Cyrillic:Medium',sans-serif] leading-[1.04] relative shrink-0 text-[#141414] text-[32px] tracking-[-0.64px] w-full" data-node-id="310:871">
            242
          </p>
        </div>
      </div>
    </div>
  );
}
